spring:
  datasource:
    url: jdbc:h2:mem:app_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /console
  servlet:
    multipart:
      enabled: true
      location: /tmp
server:
  port: 9090
graphql:
  servlet:
    mapping: /api/**
graphiql:
  endpoint: /api/**

